src/Entity/Plat.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PlatRepository")
 */
class Plat
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\Length(min=3, max=50, minMessage="Le Nom est trop court ! Il doit plus de 3 lettres du con !")
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=500)
     * @Assert\Length(min=4, max=500)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $image;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\Reservation", mappedBy="plat", orphanRemoval=true)
     */
    private $resa;

    public function __construct()
    {
        $this->resa = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @return Collection|Reservation[]
     */
    public function getResa(): Collection
    {
        return $this->resa;
    }

    public function addResa(Reservation $resa): self
    {
        if (!$this->resa->contains($resa)) {
            $this->resa[] = $resa;
            $resa->setPlat($this);
        }

        return $this;
    }

    public function removeResa(Reservation $resa): self
    {
        if ($this->resa->contains($resa)) {
            $this->resa->removeElement($resa);
            // set the owning side to null (unless already changed)
            if ($resa->getPlat() === $this) {
                $resa->setPlat(null);
            }
        }

        return $this;
    }
}

src/Controller/SecurityController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Form\RegistrationType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Encoder\UserPasswordEncoderInterface;

class SecurityController extends AbstractController
{
    /**
     * @Route("/inscription", name="security_registration")
     */
    public function registration(Request $request, EntityManagerInterface $manager, UserPasswordEncoderInterface $encoder)
    {
        $user = new User();

        $form = $this->createForm(RegistrationType::class, $user);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $hash = $encoder->encodePassword($user, $user->getPassword());

            $user->setPassword($hash);

            $manager ->persist($user);
            $manager->flush();

            return $this->redirectToRoute('security_login');
        }
        
        return $this->render('security/registration.html.twig', [
            'form'=> $form->createView()
        ]);
    }
    /**
     * @Route("/login", name="security_login")
     */
    public function login()
    {
        return $this->render('security/login.html.twig');
    }
    /**
     * @Route("/logout", name="security_logout")
     */
    public function logout()
    {}
}

templates/security/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello SecurityController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'C:/Users/El Figuer/Desktop/recettes_cuisine/src/Controller/SecurityController.php'|file_link(0) }}">src/Controller/SecurityController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'C:/Users/El Figuer/Desktop/recettes_cuisine/templates/security/index.html.twig'|file_link(0) }}">templates/security/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/security/login.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <h1>Connexion !</h1>

    <form action="{{ path('security_login') }}" method="post">
        <div class="form-group">
            <input placeholder="Adresse mail" required name="_username" type="text" class="form-control">
        </div>
        <div class="form-group">
            <input placeholder="Mot de passe" required name="_password" type="text" class="form-control">
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-success">Connexion !</button>
        </div>
    </form>
{% endblock %}

templates/security/registration.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <h1>Inscription sur le site</h1>

    {{form_start(form)}}
    {{form_row(form.nom)}}
    {{form_row(form.prenom)}}
    {{form_row(form.email)}}
    {{form_row(form.password)}}
    {{form_row(form.confirm_password)}}
    <button type="submit">Inscription</button>
    {{form_end(form)}}
{% endblock %}